name: Build and Push Wrk Image

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  # schedule:
  #   - cron: '0 3 * * *' # 每天构建一次（可选）

env:
  DOCKER_REPO: bailangvvking/wrk2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Server Performance(检查服务器性能)
        run: |
          echo "警告⚠"
          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
          echo -e "已知CPU型号（降序）：7763，8370C，8272CL，8171M，E5-2673 \n"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量：$(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo -e "CPU核心信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息："
          echo -e "$(sudo lshw -short -C memory | grep GiB) \n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get latest Nginx version
        id: get_version
        run: |
          VER=$(curl -s https://nginx.org/en/download.html | grep -Eo 'nginx-[0-9]+\.[0-9]+\.[0-9]+\.tar\.gz' | head -n1 | cut -d'-' -f2 | cut -d'.' -f1-3)
          TS=$(TZ=Asia/Shanghai date '+%Y-%m-%d-%H_%M_%S')
          echo "NGINX_VERSION=$VER" >> $GITHUB_ENV
          echo "TAG=${VER}-${TS}" >> $GITHUB_ENV
          echo "Latest Nginx version: $VER, tag: ${VER}-${TS}"

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          # platforms: linux/amd64, linux/arm64, linux/riscv64
          platforms: linux/amd64,linux/arm64
          # platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:latest
            ${{ env.DOCKER_REPO }}:${{ env.TAG }}
          build-args: |
              NGINX_VERSION=${{ env.NGINX_VERSION }}
